.PHONY: clean All

All:
	@echo "==========Building project:[ VM_machine - Debug ]=========="
	@cd "VM_machine" && "$(MAKE)" -f  "VM_machine.mk"
clean:
	@echo "==========Cleaning project:[ VM_machine - Debug ]----------"
	@cd "VM_machine" && "$(MAKE)" -f  "VM_machine.mk" clean
